# Generated by Django 3.0.5 on 2020-06-12 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LU_Category',
            fields=[
                ('Category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descriptions', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LU_Item',
            fields=[
                ('Item', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descriptions', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descriptions', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LU_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=100)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.LU_Category')),
                ('Item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.LU_Item')),
            ],
            options={
                'managed': True,
                'unique_together': {('Category', 'Item', 'Value')},
            },
        ),
        migrations.CreateModel(
            name='ASO_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1000000)])),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('Product', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Product')),
                ('Value', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.LU_Value')),
            ],
            options={
                'managed': True,
                'unique_together': {('Project', 'Product', 'Value')},
            },
        ),
    ]
